// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyx2TZ2KLMlSZKpBRVPYADlRLbytyd36s',
    appId: '1:322481550402:web:87bf4f16c917bf9f7329db',
    messagingSenderId: '322481550402',
    projectId: 'safety-guardian-82aa8',
    authDomain: 'safety-guardian-82aa8.firebaseapp.com',
    storageBucket: 'safety-guardian-82aa8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRPFrGK5rqfrxWDBx5ybjtcnjuqjuy5KQ',
    appId: '1:322481550402:android:37f60520d4219a527329db',
    messagingSenderId: '322481550402',
    projectId: 'safety-guardian-82aa8',
    storageBucket: 'safety-guardian-82aa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_35-UBrWz5DcM-fEh9AlUfFg_djnvUzQ',
    appId: '1:322481550402:ios:69e274510d6feda67329db',
    messagingSenderId: '322481550402',
    projectId: 'safety-guardian-82aa8',
    storageBucket: 'safety-guardian-82aa8.firebasestorage.app',
    iosBundleId: 'com.safety.guardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_35-UBrWz5DcM-fEh9AlUfFg_djnvUzQ',
    appId: '1:322481550402:ios:69e274510d6feda67329db',
    messagingSenderId: '322481550402',
    projectId: 'safety-guardian-82aa8',
    storageBucket: 'safety-guardian-82aa8.firebasestorage.app',
    iosBundleId: 'com.safety.guardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyx2TZ2KLMlSZKpBRVPYADlRLbytyd36s',
    appId: '1:322481550402:web:ce0f7ddb24fff29f7329db',
    messagingSenderId: '322481550402',
    projectId: 'safety-guardian-82aa8',
    authDomain: 'safety-guardian-82aa8.firebaseapp.com',
    storageBucket: 'safety-guardian-82aa8.firebasestorage.app',
  );
}
