name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Go to Flutter project
        run: cd untitled8
          
      - name: Get dependencies
        run: |
          cd untitled8
          flutter clean
          flutter pub get
          
      - name: Build APK
        run: |
          cd untitled8
          flutter build apk --release
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: safety-guardian-apk
          path: untitled8/build/app/outputs/flutter-apk/app-release.apk
